import type { GallerySnapshotItem } from "./domain/gallery.types";

export const FALLBACK_GALLERY_SNAPSHOTS: GallerySnapshotItem[] = [
  {
    id: "rinjani",
    title: "Mount Rinjani Caldera",
    subtitle: "3,726 MASL summit • Cloud sea & turquoise lake.",
    badgeTop: "3D2N Trek",
    badgeStat: "3,726 MDPL",
    badgeExtra: "Sembalun Route",
    imageUrl:
      "https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&w=800&q=80",
    rotation: "-rotate-[4deg]",
    zIndex: "z-20",
    positionClasses: "lg:top-0 lg:left-[0%] xl:left-[1%]",
    cardWidthClasses: "w-[260px] xl:w-[285px]",
    imageAspectClasses: "aspect-[4/3]",
    linkUrl: "/packages",
    displayOrder: 1,
    isActive: true,
  },
  {
    id: "secret-gili",
    title: "Secret Gili Islands",
    subtitle: "Pristine coral gardens & exotic sea turtle sanctuaries.",
    badgeTop: "Island Hopping",
    badgeStat: "ISLAND HOPPING",
    badgeExtra: "Gili Nanggu & Sudak",
    imageUrl:
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
    rotation: "rotate-[2deg]",
    zIndex: "z-10",
    positionClasses: "lg:top-0 lg:left-[35%] xl:left-[36%]",
    cardWidthClasses: "w-[250px] xl:w-[275px]",
    imageAspectClasses: "aspect-[4/3]",
    linkUrl: "/packages",
    displayOrder: 2,
    isActive: true,
  },
  {
    id: "merese",
    title: "Bukit Merese Savanna",
    subtitle: "Mandalika ocean breeze, green hills & 360° sunset.",
    badgeTop: "18:10 WITA",
    badgeStat: "GOLDEN HOUR",
    badgeExtra: "Mandalika Coast",
    imageUrl:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    rotation: "rotate-[4deg]",
    zIndex: "z-20",
    positionClasses: "lg:top-0 lg:right-[0%] xl:right-[1%]",
    cardWidthClasses: "w-[260px] xl:w-[285px]",
    imageAspectClasses: "aspect-[4/3]",
    linkUrl: "/packages",
    displayOrder: 3,
    isActive: true,
  },
  {
    id: "pink-beach",
    title: "Pink Sand Beach",
    subtitle: "Naturally tinted pink sands from red deep-sea corals.",
    badgeTop: "Highlight",
    badgeStat: "ALL-INCLUSIVE",
    badgeExtra: "Speedboat Pier",
    imageUrl:
      "https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&w=800&q=80",
    rotation: "-rotate-[1deg]",
    zIndex: "z-30",
    positionClasses: "lg:top-[135px] lg:left-[36%] xl:left-[37%]",
    cardWidthClasses: "w-[270px] xl:w-[295px]",
    imageAspectClasses: "aspect-[16/10]",
    linkUrl: "/packages",
    displayOrder: 4,
    isActive: true,
  },
  {
    id: "tiu-kelep",
    title: "Tiu Kelep Waterfall",
    subtitle: "Lush Senaru jungle with majestic refreshing cascades.",
    badgeTop: "North Lombok",
    badgeStat: "ADVENTURE",
    badgeExtra: "Forest Trek",
    imageUrl:
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
    rotation: "-rotate-[3deg]",
    zIndex: "z-10",
    positionClasses: "lg:bottom-0 lg:left-[0%]",
    cardWidthClasses: "w-[250px] xl:w-[270px]",
    imageAspectClasses: "aspect-[4/3]",
    linkUrl: "/packages",
    displayOrder: 5,
    isActive: true,
  },
  {
    id: "pusuk",
    title: "Baun Pusuk Forest",
    subtitle: "Scenic mountain pass with friendly wild monkey troops.",
    badgeTop: "Pusuk Forest",
    badgeStat: "PANORAMIC",
    badgeExtra: "Innova Chauffeur",
    imageUrl:
      "https://images.unsplash.com/photo-1549399573-970a87791404?auto=format&fit=crop&w=800&q=80",
    rotation: "rotate-[2deg]",
    zIndex: "z-20",
    positionClasses: "lg:bottom-0 lg:left-[25.5%]",
    cardWidthClasses: "w-[250px] xl:w-[270px]",
    imageAspectClasses: "aspect-[4/3]",
    linkUrl: "/rentals",
    displayOrder: 6,
    isActive: true,
  },
  {
    id: "selong-belanak",
    title: "Selong Belanak Surf",
    subtitle: "Soft coral-free sands, ideal for beginner surf lessons.",
    badgeTop: "South Coast",
    badgeStat: "BEGINNER SURF",
    badgeExtra: "South Coast",
    imageUrl:
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80",
    rotation: "-rotate-[3deg]",
    zIndex: "z-20",
    positionClasses: "lg:bottom-0 lg:right-[25.5%]",
    cardWidthClasses: "w-[250px] xl:w-[270px]",
    imageAspectClasses: "aspect-[4/3]",
    linkUrl: "/packages",
    displayOrder: 7,
    isActive: true,
  },
  {
    id: "kuta-villa",
    title: "Infinity Villa Kuta",
    subtitle: "Wake up and swim overlooking Mandalika hills and ocean.",
    badgeTop: "Turnkey Property",
    badgeStat: "EXCLUSIVE",
    badgeExtra: "Mandalika Ridge",
    imageUrl:
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80",
    rotation: "rotate-[4deg]",
    zIndex: "z-10",
    positionClasses: "lg:bottom-0 lg:right-[0%]",
    cardWidthClasses: "w-[250px] xl:w-[270px]",
    imageAspectClasses: "aspect-[4/3]",
    linkUrl: "/properties",
    displayOrder: 8,
    isActive: true,
  },
];
